API/UI split
Afterglow/docker-cyclid pull request #1
Opened 2017-02-08 19:09 UTC by Vanders

Refactor everything so that the Server, UI & Sidekiq are all built from seperate Dockerfiles.
Make the UI work reliably by setting SESSION_SECRET in the environment.

2017-02-09 19:51 UTC, Afterglow requested changes

2017-02-09 19:51 UTC, Afterglow commented on cyclid_sidekiq/Dockerfile
> +COPY files/cyclid-0.2.4.gem /tmp/
any chance you can release this to rubygems?

2017-02-09 19:51 UTC, Afterglow commented on cyclid_ui/Dockerfile
> +COPY files/cyclid-ui-0.2.2.gem /tmp/
release this too?

2017-02-09 19:51 UTC, Afterglow commented on Dockerfile
> +RUN apt-get install -qy ruby2.3 ruby2.3-dev build-essential cmake mysql-client libmysqlclient-dev libsasl2-dev nginx
is nginx necessary, i'm not sure it actually gets run at any point?

2017-02-09 19:51 UTC, Afterglow commented on cyclid_ui/files/unicorn.rb
> +#listen "/var/run/unicorn.cyclid-ui.sock"
remove this?

2017-02-09 19:52 UTC, Vanders commented on Dockerfile
> +RUN apt-get install -qy ruby2.3 ruby2.3-dev build-essential cmake mysql-client libmysqlclient-dev libsasl2-dev nginx
Yes nginx can be dropped.

2017-02-09 19:52 UTC, Vanders commented on cyclid_ui/files/unicorn.rb
> +#listen "/var/run/unicorn.cyclid-ui.sock"
Yup, missed that one.

2017-02-09 19:53 UTC, Vanders commented on cyclid_ui/Dockerfile
> +COPY files/cyclid-ui-0.2.2.gem /tmp/
Those are both custom Gems; I want to roll up some other changes and do a patch release of both Cyclid & Cyclid UI; maybe next week? I can open a PR to install from Rubygems once that's done.

2017-02-12 10:42 UTC, Afterglow approved these changes

2017-02-12 10:42 UTC, merged